version: 2.0.{build}

branches:
  only:
    - master

image: Visual Studio 2019

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration: Release

before_build:
  - nuget restore
  
build:
  project: Textile.sln

test: off

artifacts:
  - path: '**\DotNetProjects.Textile*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: bdhemLvYgto+o1hjkJ9OhVRANxW6+U9RTGQre/KqyV3mFWmN5BQA6ZpMoHbjsaJW
  artifact: /.*\.nupkg/
  
  
  